-- ============================================================
-- DELTARQ Scanner — Supabase Database Schema
-- Paste this into Supabase SQL Editor and click "Run"
-- ============================================================

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop old tables and views to cleanup and avoid conflicts
DROP VIEW IF EXISTS daily_scan_stats CASCADE;
DROP VIEW IF EXISTS lead_pipeline CASCADE;
DROP TABLE IF EXISTS report_views CASCADE;
DROP TABLE IF EXISTS leads CASCADE;
DROP TABLE IF EXISTS scans CASCADE;

-- Drop new scan tables if they exist (clean slate)
DROP TABLE IF EXISTS leads_scan CASCADE;
DROP TABLE IF EXISTS result_scan CASCADE;

-- ============================================================
-- Table: result_scan
-- Stores anonymous scan metadata from CLI tool
-- NO secrets, NO file contents, only boolean pass/fail data
-- ============================================================
CREATE TABLE result_scan (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  scan_id       TEXT UNIQUE NOT NULL,        -- UUID generated by CLI
  timestamp     TIMESTAMPTZ NOT NULL,        -- When the scan was run
  scanner_version TEXT DEFAULT '0.1.0',      -- CLI version
  project_type  TEXT DEFAULT 'unknown',      -- Detected project type (fastapi, node, etc.)
  
  -- Score metadata
  score         INTEGER NOT NULL DEFAULT 0,   -- 0-100
  grade         TEXT NOT NULL DEFAULT 'F',    -- A, B, C, D, F
  enterprise_ready BOOLEAN DEFAULT FALSE,
  
  -- Findings (anonymous — only rule ID, severity, pass/fail)
  findings      JSONB NOT NULL DEFAULT '[]'::jsonb,
  
  -- Aggregate stats
  drift_detected       BOOLEAN DEFAULT FALSE,
  compliance_gap_count INTEGER DEFAULT 0,
  
  -- Metadata
  ip_country    TEXT,                         -- Optional: country from IP (no exact IP stored)
  user_agent    TEXT,                         -- Scanner user-agent string
  
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast report lookups
CREATE INDEX IF NOT EXISTS idx_result_scan_scan_id ON result_scan(scan_id);
CREATE INDEX IF NOT EXISTS idx_result_scan_created_at ON result_scan(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_result_scan_score ON result_scan(score);

-- ============================================================
-- Table: leads_scan
-- Stores optional user info from the dashboard lead capture form
-- User fills this VOLUNTARILY after viewing their report
-- ============================================================
CREATE TABLE leads_scan (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  scan_id         TEXT REFERENCES result_scan(scan_id) ON DELETE SET NULL,
  
  -- Contact info (all optional — user fills what they want)
  company_name    TEXT,
  business_email  TEXT,
  phone_number    TEXT,
  industry        TEXT,                       -- SaaS, Fintech, Healthcare, etc.
  role            TEXT,                       -- CTO, Founder, Developer, etc.
  
  -- Business context
  average_deal_size TEXT,                     -- $50k, $100k, $250k, $500k+
  team_size       TEXT,
  
  -- Scan context (copied from scan for easy querying)
  score           INTEGER,
  grade           TEXT,
  compliance_gap_count INTEGER,
  
  -- Tracking
  source          TEXT DEFAULT 'dashboard',
  utm_source      TEXT,
  utm_medium      TEXT,
  utm_campaign    TEXT,
  
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Index for lead management
CREATE INDEX IF NOT EXISTS idx_leads_scan_email ON leads_scan(business_email);
CREATE INDEX IF NOT EXISTS idx_leads_scan_created_at ON leads_scan(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_scan_scan_id ON leads_scan(scan_id);

-- ============================================================
-- Row Level Security (RLS) Policies
-- ============================================================

-- Enable RLS on both tables
ALTER TABLE result_scan ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads_scan ENABLE ROW LEVEL SECURITY;

-- result_scan: Anyone can INSERT (CLI uploads), anyone can SELECT by scan_id (report viewing)
CREATE POLICY "Allow anonymous scan inserts" ON result_scan
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow reading scans by scan_id" ON result_scan
  FOR SELECT USING (true);

-- leads_scan: Anyone can INSERT (form submission), only authenticated users can SELECT
CREATE POLICY "Allow anonymous lead inserts" ON leads_scan
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow authenticated lead reads" ON leads_scan
  FOR SELECT USING (auth.role() = 'authenticated');

-- ============================================================
-- Updated_at trigger for result_scan table
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_result_scan_updated_at
  BEFORE UPDATE ON result_scan
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
